service: calendar
frameworkVersion: '3'

plugins:
  - '@hewmen/serverless-plugin-typescript'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  email_service:
    handler: handler.email_service
    events:
      - httpApi:
          path: /
          method: get
